### PR TITLE
Add unsecure schemes for seemless benchmarking

### PR DESCRIPTION
**Pull request by jonas-lj**
Closing #69 
Depends on PR #83

### CODE REVIEW

**Review by kchalkias — COMMENTED** [review]
Ideally and for easier PR {management + review}, let's split this PR into UnsecureSig and UnsecureHash.

**Comment by jonas-lj** [comment]
@kchalkias Would it make sense to make the unsecure signature scheme slightly more complex by creating a signature as H(public_key || message)? I think that would make benchmarking even more seemless, since verification now fails with the wrong message and/or public key.

**Comment by kchalkias** [comment]
@jonas-lj wow that's a great idea, especially when combined with the unsecure **fast** hash work. Yes I like that. I actually think it's the best first step we should take.

**Comment by jonas-lj** [comment]
> @jonas-lj wow that's a great idea, especially when combined with the unsecure **fast** hash work. Yes I like that. I actually think it's the best first step we should take.

Great, I'll do that then. I'll create a PR with the dummy hash-function and then rewrite this PR afterwards.

**Review by kchalkias — APPROVED** [review]

**Pull request merged**
