### PR TITLE
Remove redundant benchmarks

### PR DESCRIPTION
**Pull request by jonas-lj**
Only benchmark batched verification for BLS (which both aggregates and verifies) for more fair comparison with the other schemes.

### CODE REVIEW

**Review by kchalkias — COMMENTED** [review]
I want us to reconsider this, typically another entity is aggregating (ie the tx submitter forms a cert from receiving signatures from each validator) and another verifies the aggregated (the validators or blockchain users). Thus just verifying an already aggregated sig is still important.

**Comment by jonas-lj** [comment]
> I want us to reconsider this, typically another entity is aggregating (ie the tx submitter forms a cert from receiving signatures from each validator) and another verifies the aggregated (the validators or blockchain users). Thus just verifying an already aggregated sig is still important.

That definitely makes sense. I was just confused when revisiting the benchmarks after some time because it was a bit unclear to me, what the difference between "batched" and "aggregated" was here, but this could be solved with documentation.

**Review by kchalkias — COMMENTED** [review]
what's the verdict eventually? IMO we should still keep these benchmarks for reference.

**Comment by jonas-lj** [comment]
Sure, let's keep them.

**Pull request closed without merging**
