### PR TITLE
Extend the BLS library to support also min_pk using macros

### PR DESCRIPTION
**Pull request by benr-ml**
Extending the BLS code to work with both modes.
All objects exist for both modes, under different internal modules: min_sig and min_pk.

### CODE REVIEW

**Review by kchalkias — COMMENTED** [review]
So just to clarify, how external apps will use one or the other when using fastcrypto as a dep?

**Comment by kchalkias** [comment]
Ok I see, so the fastcrypto dependency will be something like `fastcrypto::bls12381::min_sig::BLS12381KeyPair`, and the end user doesn't know anything about macros etc?

**Comment by benr-ml** [comment]
@kchalkias yes, similar abstraction to what we had so far, just with additional modules to differentiate between the modes

**Review by kchalkias — APPROVED** [review]
Fantastic, let's gradually have some documentation in a related readme file (future PR), this one is good to be landed!

**Pull request merged**
